### ISSUE TITLE
Authorization issue

### ISSUE THREAD

**Issue by rinzeb** [TNOCS/excel2map#30]
When requesting a list of users for a resource (project), authorization is denied when it should be allowed. 

Problem: resource has 2 parameters, 'domain' and 'type', both of which should be equal to their counterparts in the rule object. However, only 'domain' is set in the request, 'type' remains empty. Therefore the rule never applies. 

in node-auth.ts the 'type' should be set next to the domain in the resource2JSON function: 

const resource2JSON = (req: Request, res: Response, next: NextFunction) => {
        if (req.params.hasOwnProperty('resourceID')) { req.body = Object.assign(req.body, { resource: { domain: req.params['resourceID'] } }); }
        next();
    };

**Comment by erikvullings** [comment]
Instead of using the resource ID, specify all applicable params as query object, e.g. 
api/authorizations/resources?domain=1234&type=project.
This is more flexible, because the rule that was created when creating a new project may specify any number of resource parameters to describe the resource, and node_auth doesn't know about them.
